CREATE DATABASE BUILDING_MANAGEMENT;
USE BUILDING_MANAGEMENT;

-- =====================================
-- DISTRICT
-- =====================================
CREATE TABLE DISTRICT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(50) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL
);

-- =====================================
-- BUILDING
-- =====================================
CREATE TABLE BUILDING (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    NAME VARCHAR(255) NOT NULL,

    DISTRICTID BIGINT,

    WARD VARCHAR(255),
    STREET VARCHAR(255),

    STRUCTURE VARCHAR(255),

    NUMBEROFBASEMENT INT,

    FLOOR_AREA DOUBLE,

    DIRECTION VARCHAR(50),

    BUILDING_LEVEL VARCHAR(50),

    RENT DECIMAL(15,2),

    SERVICE_PRICE DECIMAL(15,2),

    CAR_FEES DECIMAL(15,2),

    MOTO_FEES DECIMAL(15,2),

    OVERHOURS_FEES DECIMAL(15,2),

    ELECTRICITY_PAY DECIMAL(15,2),

    DEPOSIT DECIMAL(15,2),

    PAYMENT VARCHAR(255),

    RENTAL_TERM VARCHAR(255),

    DECORATION_TIME VARCHAR(255),

    MANAGER_NAME VARCHAR(255),

    MANAGER_PHONE_NUMBER VARCHAR(20),

    BROKERAGE_FEES DECIMAL(15,2),

    NOTES TEXT,

    FOREIGN KEY (DISTRICTID)
        REFERENCES DISTRICT(ID)
);

-- =====================================
-- RENT TYPE
-- =====================================
CREATE TABLE RENTTYPE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    CODE VARCHAR(50) NOT NULL UNIQUE,

    NAME VARCHAR(255) NOT NULL
);

-- =====================================
-- BUILDING - BUILDINGTYPE (N-N)
-- =====================================
CREATE TABLE BUILDINGTYPE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(50) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BUILDING_BUILDINGTYPE(
    BUILDINGID BIGINT,
    BUILDINGTYPEID BIGINT,

    PRIMARY KEY(BUILDINGID, BUILDINGTYPEID),

    FOREIGN KEY(BUILDINGID) REFERENCES BUILDING(ID),
    FOREIGN KEY(BUILDINGTYPEID) REFERENCES BUILDINGTYPE(ID)
);

-- =====================================
-- USER
-- =====================================
CREATE TABLE USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    USERNAME VARCHAR(255) NOT NULL UNIQUE,

    PASSWORD VARCHAR(255) NOT NULL
);

-- =====================================
-- ROLE
-- =====================================
CREATE TABLE ROLE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    CODE VARCHAR(50) NOT NULL UNIQUE,

    NAME VARCHAR(255) NOT NULL
);

-- =====================================
-- USER_ROLE (N-N)
-- =====================================
CREATE TABLE USER_ROLE (
    USERID BIGINT NOT NULL,
    ROLEID BIGINT NOT NULL,

    PRIMARY KEY (USERID, ROLEID),

    FOREIGN KEY (USERID)
        REFERENCES USER(ID),

    FOREIGN KEY (ROLEID)
        REFERENCES ROLE(ID)
);

-- =====================================
-- RENT AREA
-- =====================================
CREATE TABLE RENTAREA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    AREAVALUE INT NOT NULL,

    BUILDINGID BIGINT NOT NULL,

    FOREIGN KEY (BUILDINGID)
        REFERENCES BUILDING(ID)
);

-- =====================================
-- CUSTOMER
-- =====================================
CREATE TABLE CUSTOMER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    FULLNAME VARCHAR(255),

    PHONE VARCHAR(20),

    EMAIL VARCHAR(50),

    COMPANYNAME VARCHAR(255),

    DEMAND TEXT,

    STATUS VARCHAR(100)
);

-- =====================================
-- TRANSACTION TYPE
-- =====================================
CREATE TABLE TRANSACTIONTYPE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    CODE VARCHAR(50) NOT NULL UNIQUE,

    NAME VARCHAR(255) NOT NULL
);

-- =====================================
-- TRANSACTION
-- =====================================
CREATE TABLE TRANSACTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    CUSTOMERID BIGINT NOT NULL,

    TRANSACTIONTYPEID BIGINT NOT NULL,

    CREATEDATE DATETIME DEFAULT CURRENT_TIMESTAMP,

    NOTE TEXT,
	
    STATUS NVARCHAR(50),
    
    STAFFID BIGINT NOT NULL,
    FOREIGN KEY (STAFFID) REFERENCES USER(ID),
    
    FOREIGN KEY (CUSTOMERID)
        REFERENCES CUSTOMER(ID),

    FOREIGN KEY (TRANSACTIONTYPEID)
        REFERENCES TRANSACTIONTYPE(ID)
);

-- =====================================
-- ASSIGN CUSTOMER (N-N)
-- =====================================
CREATE TABLE ASSIGNMENTCUSTOMER (
    CUSTOMERID BIGINT NOT NULL,

    STAFFID BIGINT NOT NULL,

    PRIMARY KEY (CUSTOMERID, STAFFID),

    FOREIGN KEY (CUSTOMERID)
        REFERENCES CUSTOMER(ID),

    FOREIGN KEY (STAFFID)
        REFERENCES USER(ID)
);

-- =====================================
-- ASSIGN BUILDING (N-N)
-- =====================================
CREATE TABLE ASSIGNMENTBUILDING (
    BUILDINGID BIGINT NOT NULL,

    STAFFID BIGINT NOT NULL,

    PRIMARY KEY (BUILDINGID, STAFFID),

    FOREIGN KEY (BUILDINGID)
        REFERENCES BUILDING(ID),

    FOREIGN KEY (STAFFID)
        REFERENCES USER(ID)
);